export default  [
      {
        "id": "49242",
        "user_nicename": "\u8ba9\u6211\u4eec\u606d\u559c\u91cd\u5e86\u72fc\u961f*4",
        "avatar": "http:\/\/39.103.165.5\/\/upload\/\/live\/20220425\/07042319188780590.png",
        "avatar_thumb": "http:\/\/39.103.165.5\/\/upload\/\/default.jpg",
        "sex": "0",
        "signature": "This guy is too lazy to write something here",
        "consumption": "4",
        "votestotal": "0",
        "province": "",
        "city": "Seems to be on mars",
        "birthday": "",
        "user_status": "1",
        "issuper": "0",
        "location": "",
        "coin": "909",
        "fans": "7",
        "level": "1",
        "level_anchor": "1",
        "islive": 1,
        "liveid": "3394",
        "game_id": "3559904",
        "stream": "49242_1651212915",
        "is_attention": "1"
      },
      {
        "id": "49123",
        "user_nicename": "ceshi",
        "avatar": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "avatar_thumb": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "sex": "1",
        "signature": "This guy is too lazy to write something here",
        "consumption": "0",
        "votestotal": "0",
        "province": "",
        "city": "",
        "birthday": "",
        "user_status": "1",
        "issuper": "0",
        "location": "",
        "coin": "0",
        "fans": "2",
        "level": "1",
        "level_anchor": "1",
        "islive": 0,
        "liveid": 0,
        "game_id": 0,
        "stream": 0,
        "is_attention": "1"
      },
      {
        "id": "49130",
        "user_nicename": "\u8001\u5927\u7237",
        "avatar": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "avatar_thumb": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "sex": "1",
        "signature": "This guy is too lazy to write something here",
        "consumption": "0",
        "votestotal": "0",
        "province": "",
        "city": "",
        "birthday": "",
        "user_status": "1",
        "issuper": "0",
        "location": "",
        "coin": "820",
        "fans": "3",
        "level": "1",
        "level_anchor": "1",
        "islive": 0,
        "liveid": 0,
        "game_id": 0,
        "stream": 0,
        "is_attention": "1"
      },
      {
        "id": "49131",
        "user_nicename": "admin",
        "avatar": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "avatar_thumb": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "sex": "0",
        "signature": "This guy is too lazy to write something here",
        "consumption": "0",
        "votestotal": "0",
        "province": "",
        "city": "",
        "birthday": "",
        "user_status": "1",
        "issuper": "0",
        "location": "",
        "coin": "0",
        "fans": "1",
        "level": "1",
        "level_anchor": "1",
        "islive": 0,
        "liveid": 0,
        "game_id": 0,
        "stream": 0,
        "is_attention": "1"
      },
      {
        "id": "49137",
        "user_nicename": "\u968f\u4fbf",
        "avatar": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "avatar_thumb": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "sex": "1",
        "signature": "This guy is too lazy to write something here",
        "consumption": "1071901",
        "votestotal": "0",
        "province": "",
        "city": "1",
        "birthday": "",
        "user_status": "1",
        "issuper": "0",
        "location": "",
        "coin": "1110039489",
        "fans": "2",
        "level": "20",
        "level_anchor": "1",
        "islive": 0,
        "liveid": 0,
        "game_id": 0,
        "stream": 0,
        "is_attention": "1"
      },
      {
        "id": "49138",
        "user_nicename": "\u7403\u9738",
        "avatar": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "avatar_thumb": "http:\/\/39.103.165.5\/\/upload\/\/default.png",
        "sex": "0",
        "signature": "This guy is too lazy to write something here",
        "consumption": "0",
        "votestotal": "0",
        "province": "",
        "city": "",
        "birthday": "",
        "user_status": "1",
        "issuper": "0",
        "location": "",
        "coin": "6",
        "fans": "1",
        "level": "1",
        "level_anchor": "1",
        "islive": 0,
        "liveid": 0,
        "game_id": 0,
        "stream": 0,
        "is_attention": "1"
      }
    ]